amqp.host: localhost
amqp.port: 5672
amqp.user: guest
amqp.pswd: guest

folder.temp: ./temp
folder.images_resized: ./images_resized

gdrive.clientid: 876807043295-qqnceudc50rcqglbdiqjaoslmt68f3g0.apps.googleusercontent.com
gdrive.secret: 92bHI5uNIMEXjfmroYYomIw2
