amqp.host: localhost
amqp.port: 5672
amqp.user: guest
amqp.pswd: guest

folder.temp: ./temp
folder.images_resized: ./images_resized

gdrive.credentials.path: ~/.credentials/gdrive.json
gdrive.client_secret_path: ~/.credentials/gdrive-secret.json
gdrive.redirect_uri: https://oauth2-login-demo.appspot.com/oauthcallback
